# Define rate limit zone (this is allowed here)
limit_req_zone $binary_remote_addr zone=perip:10m rate=15r/m;

server {
    listen 80;
    index index.php index.html;
    server_name localhost;
    root /var/www/public;

    access_log /var/log/nginx/localhost.access.log;
    error_log /var/log/nginx/localhost.error.log;

    location / {
        # Apply rate limiting
        limit_req zone=perip burst=2 nodelay;

        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        # Apply rate limiting to PHP requests too
        limit_req zone=perip burst=2 nodelay;

        fastcgi_pass app:9000;
        fastcgi_index index.php;

        include fastcgi.conf;

        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    location ~ /\.ht {
        deny all;
    }
}